export { SimulationManager } from './SimulationManager.js'
export type { SimulationSnapshot } from './SimulationManager.js'
export { CompanyManager } from './company/index.js'
export { HRManager } from './hr/index.js'
export { ProductManager, FEATURE_STATES } from './product/index.js'
export type { Feature, Bug } from './product/index.js'
export { SalesManager } from './sales/index.js'
export type { FunnelStats } from './sales/index.js'
export { FinanceManager } from './finance/index.js'
export { MarketSimulation } from './market/index.js'
